### PR TITLE
Updates tdm.pio to correct samples per frame and parameterise

### PR DESCRIPTION
**Pull request by NigelOrr-Imenco**
Noted x values were too high for 32 samples, calculated correct values and parameterised
Thanks for posting this just when I needed it :-)

### CODE REVIEW

**Comment by JohannesRgnr** [comment]
Thanks for the x values and parametrization! Haven't yet tested with a DAC, but this looks good on a logic analyzer.

**Comment by NigelOrr-Imenco** [comment]
You're welcome, many thanks for putting this up. I will push back any more progress once I get it talking to hardware. I've also added a receiver so will test those against each other as well as logic analyser.

I saw you changed frame sync to go high on last cycle of last bit, is that a TDM only sequence, or is it used for I2S? There seem to be a few flavours of TDM (part of parameterising it is because mine needs LRCK to only be high for the first channel, rather than the 50% duty cycle you had), and I'm learning as I go.

Nigel

**Comment by JohannesRgnr** [comment]
Yes, the frame synchronization is not really standardized in TDM, as far as I understand. The rising edge is the beginning of the frame, but no idea if the pulse width and falling edge are taken into account. I guess it depends on the DAC.
 So far I only checked with a Salae + https://github.com/bitswype/saleae_tdm_analyer , it looks alright ( I am pretty new to the PIO usage, and learning also these audio protocols as I go). 

I changed originally the frame sync (high on the last bit), to adapt it to the clocking of a MiniDSP MCHStreamer (that's what a colleague use here), for testing purposes. https://www.minidsp.com/images/documents/MCHStreamer%20User%20Manual.pdf
I will need to implement a slave mode (the MiniDSP only works as master), and see how that goes. 

Thanks again, the parametrization of the frame clock is really nice to have!

**Comment by NigelOrr-Imenco** [comment]
That's useful. Thanks. We are interfacing with a variety of hardware (Beaglebone Black McASP port, Cirrus Logic TDM codec (transmit only, acting as a DAC), and custom FPGA code), so expecting to learn a lot about TDM. Hopefully that assortment of experience will improve the PIO code you've kindly shared!

We have access to fancy Tektronix analysers, but I'm currently finding the workflow of PulseView and a £10 FX2 device is much faster, even though this is up at the top of its sample rate (48MHz max).

Nigel

**Pull request merged**
